#include "cli_defs.h"
#include "cli_opts.h"
#include "datasets/data_files.h"

struct option facies_long_options[] = {
    {"use-cpu", no_argument, 0, OPT_USE_CPU},
    {"gpu-device", required_argument, 0, OPT_GPU_DEVICE},
    {"input-path", required_argument, 0, OPT_INPUT_PATH},
    {"manual-seed", required_argument, 0, OPT_MANUAL_SEED},
    {"output-fullpath", required_argument, 0, OPT_OUTPUT_FULLPATH},
    {"output-path", required_argument, 0, OPT_OUTPUT_PATH},
    {"stop-scale", required_argument, 0, OPT_STOP_SCALE},
    {"num-img-channels", required_argument, 0, OPT_NUM_IMG_CHANNELS},
    {"crop-size", required_argument, 0, OPT_CROP_SIZE},
    {"batch-size", required_argument, 0, OPT_BATCH_SIZE},
    {"num-parallel-scales", required_argument, 0, OPT_NUM_PARALLEL_SCALES},
    {"num-train-pyramids", required_argument, 0, OPT_NUM_TRAIN_PYRAMIDS},
    {"num-workers", required_argument, 0, OPT_NUM_WORKERS},
    {"use-profiler", no_argument, 0, OPT_USE_PROFILER},
    {"noise-channels", required_argument, 0, OPT_NOISE_CHANNELS},
    {"num-features", required_argument, 0, OPT_NUM_FEATURES},
    {"min-num-features", required_argument, 0, OPT_MIN_NUM_FEATURES},
    {"kernel-size", required_argument, 0, OPT_KERNEL_SIZE},
    {"num-layers", required_argument, 0, OPT_NUM_LAYERS},
    {"stride", required_argument, 0, OPT_STRIDE},
    {"padding-size", required_argument, 0, OPT_PADDING_SIZE},
    {"noise-amp", required_argument, 0, OPT_NOISE_AMP},
    {"min-noise-amp", required_argument, 0, OPT_MIN_NOISE_AMP},
    {"scale0-noise-amp", required_argument, 0, OPT_SCALE0_NOISE_AMP},
    {"generator-steps", required_argument, 0, OPT_GENERATOR_STEPS},
    {"discriminator-steps", required_argument, 0, OPT_DISCRIMINATOR_STEPS},
    {"lambda-grad", required_argument, 0, OPT_LAMBDA_GRAD},
    {"alpha", required_argument, 0, OPT_ALPHA},
    {"lambda-diversity", required_argument, 0, OPT_LAMBDA_DIVERSITY},
    {"beta1", required_argument, 0, OPT_BETA1},
    {"lr-g", required_argument, 0, OPT_LR_G},
    {"lr-d", required_argument, 0, OPT_LR_D},
    {"lr-decay", required_argument, 0, OPT_LR_DECAY},
    {"save-interval", required_argument, 0, OPT_SAVE_INTERVAL},
    {"num-real-facies", required_argument, 0, OPT_NUM_REAL_FACIES},
    {"num-generated-per-real", required_argument, 0,
     OPT_NUM_GENERATED_PER_REAL},
    {"num-iter", required_argument, 0, OPT_NUM_ITER},
    {"wells-mask-columns", required_argument, 0, OPT_WELLS_MASK_COLUMNS},
    {"use-wells", no_argument, 0, OPT_USE_WELLS},
    {"well-loss-penalty", required_argument, 0, OPT_WELL_LOSS_PENALTY},
    {"use-seismic", no_argument, 0, OPT_USE_SEISMIC},
    {"no-tensorboard", no_argument, 0, OPT_NO_TENSORBOARD},
    {"no-plot-facies", no_argument, 0, OPT_NO_PLOT_FACIES},
    {"compile-backend", no_argument, 0, OPT_COMPILE_BACKEND},
    {"use-mlx", no_argument, 0, OPT_USE_MLX},
    {"hand-off-to-c", no_argument, 0, OPT_HAND_OFF_TO_C},
    {0, 0, 0, 0}};

const char *facies_help_lines[] = {
    "faciesgan usage:",
    "  -h, --help                          Show this help text",
    "  -i <path>, --input-path <path>     Input data root (must "
    "contain " DF_DIR_FACIES "/)",
    "  -o <path>, --output-path <path>    Output directory (default: results)",
    "      --output-fullpath <path>       Use exact output path (no timestamp)",
    "  -n <n>, --num-iter <n>             Iterations per scale",
    "      --use-cpu                      Run on CPU",
    "      --gpu-device <id>              GPU device id (default 0)",
    "      --manual-seed <seed>           RNG manual seed",
    "      --stop-scale <n>               Stop training at this scale",
    "      --num-img-channels <n>         Number of image channels",
    "      --img-color-range lo,hi        Image color range (lo,hi)",
    "      --crop-size <px>               Crop size for training",
    "      --batch-size <n>               Batch size",
    "      --num-parallel-scales <n>      Number of parallel scales",
    "      --num-train-pyramids <n>       Number of training pyramids",
    "      --num-workers <n>              Data loader worker count",
    "      --use-profiler                 Enable profiler hooks",
    "      --noise-channels <n>           Noise channels for generator",
    "      --num-features <n>             Base feature count for generator",
    "      --min-num-features <n>         Minimum feature maps",
    "      --kernel-size <n>              Convolution kernel size",
    "      --num-layers <n>               Number of layers in blocks",
    "      --stride <n>                   Convolution stride",
    "      --padding-size <n>             Padding size for convolutions",
    "      --noise-amp <f>                Noise amplitude",
    "      --min-noise-amp <f>            Minimum noise amplitude",
    "      --scale0-noise-amp <f>         Scale-0 noise amplitude",
    "      --generator-steps <n>          Generator steps per iteration",
    "      --discriminator-steps <n>      Discriminator steps per iteration",
    "      --lambda-grad <f>              Gradient penalty weight",
    "      --alpha <f>                    Alpha (used for some losses)",
    "      --lambda-diversity <f>         Diversity loss weight",
    "      --beta1 <f>                    Adam beta1",
    "      --lr-g <f>                     Generator learning rate",
    "      --lr-d <f>                     Discriminator learning rate",
    "      --lr-decay <n>                 Learning-rate decay (epochs)",
    "      --save-interval <n>            Save model every n iterations",
    "      --num-real-facies <n>          Number of real facies classes",
    "      --num-generated-per-real <n>   Generated samples per real facies",
    "      --wells-mask-columns c1,c2..   Columns to mask from well logs",
    "      --use-wells                    Use well data during training",
    "      --well-loss-penalty <f>        Penalty weight for well-loss "
    "(ignored)",
    "      --use-seismic                  Use seismic data during training",
    "      --no-tensorboard               Disable tensorboard logging",
    "      --no-plot-facies               Disable facies plotting",
    "      --compile-backend              Compile C backend before running",
    "      --use-mlx                      Use MLX backend instead of CUDA",
    "      --hand-off-to-c                Hand off execution to compiled C "
    "trainer",
    NULL};
