#ifndef C_TRAINER_H
#define C_TRAINER_H

#include <mlx/c/stream.h>
#include "../options.h"

int c_trainer_run(int num_samples, int num_scales, int channels, int height, int width, int batch_size);

/* Run trainer using a populated TrainningOptions struct (convenience wrapper).
 * The C implementation will map the fields and call the internal runner. */
int c_trainer_run_with_opts(const TrainningOptions *opts);

/* Extended runner that loads real pyramids from disk (generated by the
 * Python helper) when `input_path` is provided. Parameters:
 *  - input_path: root dataset path (may be NULL to keep synthetic data)
 *  - output_path: base output path used to store generated caches
 *  - manual_seed: seed for deterministic generation (-1 = random)
 *  - use_wells/use_seismic: booleans (0/1) to include conditioning channels
 *  - num_train_pyramids: number of samples to consume
 *  - num_scales: number of pyramid scales
 *  - num_img_channels: number of image channels
 *  - crop_size: per-sample crop size (height/width)
 *  - batch_size: data loader batch size
 *  - save_interval: checkpoint interval (not used by demo, passed through)
 */
int c_trainer_run_full(
    const char *input_path,
    const char *output_path,
    int manual_seed,
    int use_wells,
    int use_seismic,
    int num_train_pyramids,
    int num_scales,
    int num_img_channels,
    int crop_size,
    int batch_size,
    int save_interval);

#endif
